//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPin.Functions
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrAcc
    {
        public int Id { get; set; }
        public string CurrAccCode { get; set; }
        public string CurrAccName { get; set; }
        public string TaxOffice { get; set; }
        public string TaxNumber { get; set; }
        public Nullable<int> GroupId { get; set; }
        public string Country { get; set; }
        public string City { get; set; }
        public string District { get; set; }
        public string Address { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string Fax1 { get; set; }
        public string Fax2 { get; set; }
        public string Web { get; set; }
        public string Mail { get; set; }
        public string Contact { get; set; }
        public string ContactMail { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> CreatedUserId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedUserId { get; set; }
    }
}
