//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPin.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ERPinDbContext : DbContext
    {
        public ERPinDbContext()
            : base("name=ERPinDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CashAcc> CashAcc { get; set; }
        public virtual DbSet<CashTransaction> CashTransaction { get; set; }
        public virtual DbSet<CurrAcc> CurrAcc { get; set; }
        public virtual DbSet<CurrAccGroup> CurrAccGroup { get; set; }
        public virtual DbSet<CurrAccTransaction> CurrAccTransaction { get; set; }
        public virtual DbSet<Inventory> Inventory { get; set; }
        public virtual DbSet<InventoryGroup> InventoryGroup { get; set; }
    }
}
